### ISSUE TITLE
[Bug] VPC flow logs are not configured properly

### ISSUE THREAD

**Issue by tdmalone** [awslabs/service-workbench-on-aws#974]
**Describe the bug**

The 'initial-stack' CloudFormation stack generated to onboard an account to Service Workbench includes the following definition for a VPC-wide log group:

```
  FlowLogVPC:
    Type: AWS::EC2::FlowLog
    Condition: enableFlowLogs
    Properties:
      ResourceId:
        Ref: VPC
      ResourceType: VPC
      TrafficType: ACCEPT
      DeliverLogsPermissionArn:
        Fn::GetAtt:
          - CrossAccountRoleEnvMgmt
          - Arn
      LogGroupName: VPCLogGroup
      LogFormat: ${version} ${vpc-id} ${subnet-id} ${instance-id} ${srcaddr}
        ${dstaddr} ${srcport} ${dstport} ${protocol} ${tcp-flags} ${type}
        ${pkt-srcaddr} ${pkt-dstaddr}
```

A log group named `VPCLogGroup` doesn't exist (potentially this is meant to be `!Ref VPCLogGroup`, and a separate definition created for that log group?), and the `CrossAccountRoleEnvMgmt` role only has access to create/put to a log group with a namespaced name, which won't match the name `VPCLogGroup`:

```
              Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource:
                - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${Namespace}-*:*
                - Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${Namespace}-*:log-stream:*
```

**To Reproduce**
1. Install Service Workbench
2. Onboard at least one AWS account
3. Verify, on the `initial-stack-0000000000000` VPC, that:
   - the 'Destination name' for the VPC flow logs setting is `VPCLogGroup`,
   - a CloudWatch log group by that name doesn't exist, and
   - the IAM role attached to the flow log setting (`initial-stack-0000000000000-xacc-env-mgmt`) doesn't have create or put access for a log group called `VPCLogGroup`

**Expected behavior**
Flow logs configuration to use a namespaced log group, and VPC flow logs to flow through to it.

**Screenshots**
<img width="1140" alt="image" src="https://user-images.githubusercontent.com/900469/165235798-952615a1-85a9-45ac-a505-a2a72d2dd90a.png">

**Versions (please complete the following information):**
 - 5.0.0

**Additional context**
The same problem looks to exist for `PublicSubnet1LogGroup` as well.
